version: '3.8'

services:
  web:
    # Labels for Watchtower and Traefik
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.root66.rule=Host(`root66tulsa.club`)"
      - "traefik.http.routers.root66.entrypoints=websecure"
      - "traefik.http.routers.root66.tls=true"
      - "traefik.http.services.root66.loadbalancer.server.port=8000"
      - "traefik.docker.network=web"
      - "traefik.http.routers.root66.tls.certresolver=leresolver" 
    ports: !reset []
    networks:
      - web

networks:
  web:
    external: true